### ISSUE TITLE
Error while trying to start a robot again 

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/0-robot#91]
## Scenario
1- Connect to 2 running robots that are using same template repo.. first one is running on 6600 and the second one is running on 6602.
2- kill both of them.
3- Try to restart the the first robot server (that was running on 6600), it will crash giving the following error.

```
[Thu15 13:19] - pywsgi.py           :1146:j.zerorobot                    - INFO     - ::1 - - [2018-02-15 13:19:51] "GET /services?template_uid=github.com%2Fopenvcloud%2F0-templates%2Fopenvcloud%2F0.0.1&name=be-g8-4 HTTP/1.1" 200 308 0.001489
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f04bc5da048>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6602): Max retries exceeded with url: /services?template_uid=github.com%2Fopenvcloud%2F0-templates%2Fopenvcloud%2F0.0.1&name=be-g8-4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04bc5da048>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zrobot", line 25, in <module>
    entry_point()
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/cli/server.py", line 40, in start
    robot.start(listen=listen)
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/robot.py", line 111, in start
    self._load_services()
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/robot.py", line 155, in _load_services
    service.validate()
  File "/opt/code/github/openvcloud/0-templates/templates/vdcuser/vdcuser.py", line 19, in validate
    ovcs = self.api.services.find(template_uid=OVC_TEMPLATE, name=self.data.get('openvcloud', None))
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/dsl/ZeroRobotAPI.py", line 63, in find
    for service in robot.services.find(**kwargs):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/dsl/ZeroRobotManager.py", line 98, in find
    services, _ = self._client.api.services.listServices(query_params=kwargs)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerorobot/client/services_service.py", line 160, in listServices
    resp = self.client.get(uri, None, headers, query_params, content_type)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerorobot/client/http_client.py", line 71, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerorobot/client/http_client.py", line 53, in _handle_data
    res = method(uri, headers=headers, params=params)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6602): Max retries exceeded with url: /services?template_uid=github.com%2Fopenvcloud%2F0-templates%2Fopenvcloud%2F0.0.1&name=be-g8-4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04bc5da048>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='localhost', port=6602): Max retries exceeded with url: /services?template_uid=github.com%2Fopenvcloud%2F0-templates%2Fopenvcloud%2F0.0.1&name=be-g8-4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04bc5da048>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by zaibon** [comment]
The problem is your vdc service does some check when 0-robot starts, to make sure the associated account still exists somewhere. To so so, it uses `self.api.services.find`, This method will try to contact all the known robots to look for the account service. But since one of your robot is not started, it fails with a connection error.

I guess a simple solution would be to not fail on that, but just skip the robot we can't reach. But then that means the vdc service will fail to load too. In this case, what should we do? Not load the vdc services,  panic and stop the 0-robot ? Not sure what's the best approach

**Comment by muhamadazmy** [comment]
This is a hard chicken/egg problem, since the objects are split over 2 robots, and there is some sort of dependencies between them. 

Since the 2 (or more) robots are part of cluster, and obviously all of them must be running for the robots and services to function, we need to make sure robots are actually (working) before loading the services.

I suggest the following start procedure
- Robot starts 
- It checks for the other (configured) robots connections
- It tries to establish a connection to the other robot
- If a connection is established, continue to the service loading
- If connection is not established, it waits (tries every second or something) until a connection is established to all other robots, then proceed

Note: the robot, even if it's not fully loaded should be able to respond to 'is alive' calls so if 2 robots knows each other, both of them will block until the other is ready, hence a robot once started should report that it's reachable, so both of them can unblock

**Comment by zaibon** [comment]
Proposed solution for this:
When the validate method of a service raise an exception, we still index the service, but we don't start it. Which mean new tasks can be added to the task list but the service will not process the task list until it can execute the validate method without problem.
With this solution:
 - we don't block the robot from starting because of a missing dependecies of a service,
- the services that failed to load, will automaticlly start processsing task as soon as it is healthy again

**Comment by muhamadazmy** [comment]
What will bring the service back to a healthy state? How would u know a service validate method has failed because it depends on a service that is not available yet (host robot was down) or because of any other reason ?

**Comment by zaibon** [comment]
I don't think it really matters what is the reason it failed, but if needed we could catch some specific exception.

About what's going to bring the service back to healthy state. I'll have a routine that keeps trying to execute the validate method
